### ISSUE TITLE
A problem in using the igscout

### ISSUE THREAD

**Issue by zenghk** [Immunotools/igscout#1]
Traceback (most recent call last):
  File "igscout-master/tandem_cdr3_finder.py", line 561, in <module>
    OutputDDMatrix(d_genes, all_ds, tandem_ds, os.path.join(output_dir, "dd_heatmap.pdf"), label)
  File "igscout-master/tandem_cdr3_finder.py", line 204, in OutputDDMatrix
    sns.heatmap(matrix, cmap = 'jet', xticklabels = all_ds, yticklabels = all_ds, annot = np.array(annot_matrix), fmt = '', cbar = False, square = True, linewidth = .1, linecolor = 'grey', annot_kws = {'size' : 10})
  File "/zzh_gpfs/apps/python/lib/python2.7/site-packages/seaborn/matrix.py", line 446, in heatmap
    plotter.plot(ax, cbar_ax, kwargs)
  File "/zzh_gpfs/apps/python/lib/python2.7/site-packages/seaborn/matrix.py", line 235, in plot
    if self.annot:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

I am using the dataset downloaded from SRA. But I meet the problem above, I use the Bioproject PRJNA308641 to test the script and meet the same problem, the CDR3 region is extracted according to the result MIXCR and default D reference is used.

**Comment by yana-safonova** [comment]
Hi zenghk ,

Thank you for reporting the issue! Could you please attach your input CDR3 sequences to this thread so I can run IgScout and reproduce the bug?

Best regards,
Yana

**Comment by zenghk** [comment]
[SRR3099459.zip](https://github.com/Immunotools/igscout/files/3559382/SRR3099459.zip)
The cdr3 file I used is uploaded. I find the previous problem can be solved by removing the step sns.heatmap in OutputDDMatirx function, and I calculate the result by myself. I also meet the problem in the following, But I can get part of the result and I cannot make sure I get the whole result.
The usage of my command is python igscout-master/tandem_cdr3_finder.py igscout-master/germline_data/human/IGHD.fa SRR3099459.fasta result_SRR3099459
and I meet the problem 
File "igscout-master/tandem_cdr3_finder.py", line 595, in <module>
    if int(dd[0][1:]) < int(dd[1][1:]):
ValueError: invalid literal for int() with base 10: 'GHD6-13'

The version of my python and some of the module is listed:
python 2.7.8
seaborn                0.9.0
numpy                  1.16.4
pandas                 0.24.2
matplotlib             3.0.2
biopython              1.73
